"""Tests for report generation."""

from __future__ import annotations

from blunder_butler.aggregate import compute_summary
from blunder_butler.models import (
    Color,
    GameResult,
    ParsedGame,
    TimeControl,
)
from blunder_butler.report import generate_report


def _make_game() -> ParsedGame:
    return ParsedGame(
        game_id="game1",
        white="testplayer",
        black="opponent",
        result=GameResult.WIN,
        date="2024.01.15",
        time_control_raw="600",
        time_control=TimeControl.BLITZ,
        rated=True,
        player_color=Color.WHITE,
        moves_san=[],
        fens=[],
        clock_times=[],
    )


def test_report_has_sections(sample_analyses):
    games = [_make_game()]
    summary = compute_summary(sample_analyses, games, "testplayer")
    report = generate_report(summary)

    assert "# Chess Coaching Report: testplayer" in report
    assert "## Overall Performance" in report
    assert "## Performance by Game Phase" in report
    assert "## Worst Moves" in report
    assert "## Training Recommendations" in report


def test_report_contains_stats(sample_analyses):
    games = [_make_game()]
    summary = compute_summary(sample_analyses, games, "testplayer")
    report = generate_report(summary)

    assert "ACPL" in report
    assert "Blunders" in report
    assert "Opening" in report or "Middlegame" in report or "Endgame" in report


def test_report_has_recommendations(sample_analyses):
    games = [_make_game()]
    summary = compute_summary(sample_analyses, games, "testplayer")
    report = generate_report(summary)

    assert "Training Recommendations" in report
    # Should have at least one recommendation
    assert "1." in report


def test_report_empty_games():
    summary = compute_summary([], [], "testplayer")
    report = generate_report(summary)
    assert "testplayer" in report
    assert "Generated by Blunder Butler" in report
